"use client";
import { useActionState } from "react";
import { changeBuyerPasswordAction, updateBuyerProfileAction } from "@/lib/buyer-auth-actions";
import { ToastFeedback } from "@/components/Toast";
import Link from "next/link";

function Notice({ state }: { state: { error?: string; message?: string } | undefined }) { return <ToastFeedback error={state?.error} success={state?.message} />; }
export function ProfileForms({ profile, callbackUrl }: { profile: { name: string; email: string | null; phone: string | null; hasPassword: boolean }; callbackUrl?: string }) {
  const [profileState, profileAction, profilePending] = useActionState(updateBuyerProfileAction, undefined);
  const [passwordState, passwordAction, passwordPending] = useActionState(changeBuyerPasswordAction, undefined);
  const input = "mt-1 min-h-11 w-full rounded-xl border border-sand-300 px-3";
  return <div className="grid gap-5 md:grid-cols-2"><form action={profileAction} className="space-y-4 rounded-2xl border border-sand-200 bg-white p-6">{callbackUrl && <input type="hidden" name="callbackUrl" value={callbackUrl}/>}<h2 className="font-extrabold">Data profil</h2><Notice state={profileState}/><label className="block text-sm font-bold">Nama<input name="name" defaultValue={profile.name} required className={input}/></label><label className="block text-sm font-bold">Email<input value={profile.email ?? ""} disabled className={input}/></label><label className="block text-sm font-bold">Nomor WhatsApp<input name="phone" defaultValue={profile.phone ?? ""} required className={input}/></label><button disabled={profilePending} className="rounded-xl bg-brand-600 px-4 py-3 text-sm font-extrabold text-white">{callbackUrl ? "Simpan & Kembali ke Checkout" : "Simpan profil"}</button></form>{profile.hasPassword ? <form action={passwordAction} className="space-y-4 rounded-2xl border border-sand-200 bg-white p-6"><h2 className="font-extrabold">Ganti kata sandi</h2><Notice state={passwordState}/>{[["currentPassword","Kata sandi saat ini"],["newPassword","Kata sandi baru"],["confirmPassword","Ulangi kata sandi baru"]].map(([name,label]) => <label key={name} className="block text-sm font-bold">{label}<input name={name} type="password" required minLength={8} className={input}/></label>)}<button disabled={passwordPending} className="rounded-xl bg-brand-600 px-4 py-3 text-sm font-extrabold text-white">Ganti kata sandi</button></form> : <section className="rounded-2xl border border-brand-200 bg-brand-50 p-6"><p className="text-xs font-extrabold uppercase tracking-wider text-brand-700">Akun Google</p><h2 className="mt-2 font-extrabold text-sand-900">Kamu masuk tanpa kata sandi</h2><p className="mt-2 text-sm leading-6 text-sand-600">Gunakan tombol Google saat masuk. Jika ingin menambahkan kata sandi, kirim tautan melalui fitur lupa kata sandi.</p><Link href={`/account/forgot-password?email=${encodeURIComponent(profile.email ?? "")}`} className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-brand-600 px-4 text-sm font-extrabold text-white">Buat kata sandi</Link></section>}</div>;
}
