import Link from "next/link";
import { notFound } from "next/navigation";
import { api,ApiError } from "@/lib/api";
import { formatRupiah,formatTanggal } from "@/lib/format";
import { DestructiveActionForm } from "@/components/DestructiveActionForm";
import { archiveSeller } from "../../management-actions";
type Detail={id:string;slug:string;businessName:string;description:string|null;contactEmail:string|null;contactPhone:string|null;status:string;statusReason:string|null;registeredAt:string;account:{name:string;email:string;isActive:boolean;lastLoginAt:string|null}|null;summary:{eventCount:number;orderCount:number;transactionValue:number};salesEvents:Array<{id:string;title:string;status:string;createdAt:string;_count:{orders:number;items:number}}> ;auditEvents:Array<{id:string;action:string;actorType:string;createdAt:string;metadata:unknown}>};
export default async function SellerDetailPage({params}:{params:Promise<{id:string}>}){const{id}=await params;let seller:Detail;try{seller=await api.get<Detail>(`/admin/sellers/${id}`)}catch(e){if(e instanceof ApiError&&e.status===404)notFound();throw e}return <div className="space-y-6"><Link href="/penjual" className="text-sm font-bold text-brand-700">← Daftar Penjual</Link><header><h1 className="text-3xl font-extrabold text-sand-900">{seller.businessName}</h1><p className="mt-1 text-sm text-sand-500">/s/{seller.slug} · {seller.contactEmail} · {seller.contactPhone}</p>{seller.statusReason&&<p className="mt-3 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-900">{seller.statusReason}</p>}</header><section className="grid gap-3 sm:grid-cols-4"><Stat label="Status" value={seller.status}/><Stat label="Batch PO" value={seller.summary.eventCount}/><Stat label="Pesanan" value={seller.summary.orderCount}/><Stat label="Nilai transaksi" value={formatRupiah(seller.summary.transactionValue)}/></section><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-sand-200 bg-white"><h2 className="border-b border-sand-100 p-4 text-lg font-extrabold">Histori Batch PO</h2><div className="divide-y divide-sand-100">{seller.salesEvents.map(e=><Link key={e.id} href={`/pre-orders/${e.id}`} className="flex justify-between gap-3 p-4 hover:bg-sand-50"><div><p className="font-bold">{e.title}</p><p className="text-xs text-sand-500">{formatTanggal(e.createdAt)} · {e._count.items} varian</p></div><div className="text-right"><p className="text-xs font-bold text-brand-700">{e.status}</p><p className="text-xs text-sand-500">{e._count.orders} pesanan</p></div></Link>)}{seller.salesEvents.length===0&&<p className="p-8 text-center text-sand-500">Belum ada Batch PO.</p>}</div></section><section className="rounded-2xl border border-sand-200 bg-white"><h2 className="border-b border-sand-100 p-4 text-lg font-extrabold">Histori pengelolaan</h2><div className="divide-y divide-sand-100">{seller.auditEvents.map(a=><div key={a.id} className="p-4"><p className="font-bold text-sand-800">{a.action.replaceAll("_"," ")}</p><p className="text-xs text-sand-500">{a.actorType} · {formatTanggal(a.createdAt)}</p></div>)}{seller.auditEvents.length===0&&<p className="p-8 text-center text-sand-500">Belum ada audit aktivitas.</p>}</div></section></div><section><h2 className="mb-3 text-lg font-extrabold text-sand-900">Kontrol data</h2><DestructiveActionForm action={archiveSeller.bind(null,id)} target={seller.slug}/><p className="mt-2 text-xs text-sand-500">Seller dengan histori akan disuspend dan storefront serta Batch PO dinonaktifkan tanpa menghapus transaksi.</p></section></div>}
function Stat({label,value}:{label:string;value:React.ReactNode}){return <div className="rounded-2xl border border-sand-200 bg-white p-4"><p className="text-xs font-bold uppercase text-sand-500">{label}</p><p className="mt-1 text-xl font-extrabold text-sand-900">{value}</p></div>}
